version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      # Prepare circleci
      - node/install:
          node-version: '14.15'         
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
      # install frontend dependencies
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
       
      - run:
      # install backend dependencies
          name: Install API Dependencies
          command: |
           npm run backend:install

      - run:
      # build frontend production
       name: Front-End Build
          command: |
           npm run frontend:build

      - run:
      # build backend production
       name: Back-End Build
          command: |
           npm run backend:build

      - run:
      # deploy production frontend to s3 bucket
          name: Deploy Frontend
          command: |
            npm run frontend:deploy

      - run:
      # deploy production backend to elasticbeanstalk
          name: Deploy Backend
          command: |
            npm run backend:deploy
            
            
workflows:
  udagram:
    jobs:
      - build and debloy:
          filters:
            branches:
              only: main
